#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-atinject
Version  : 2.4.0.b34
Release  : 2
URL      : https://repo1.maven.org/maven2/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
Source0  : https://repo1.maven.org/maven2/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
Source1  : https://repo1.maven.org/maven2/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-atinject-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-atinject package.
Group: Data

%description data
data components for the mvn-atinject package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar
/usr/share/java/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.pom
